# Generated by Django 4.2.22 on 2025-07-01 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0002_initial'),
        ('products', '0001_initial'),
        ('customers', '0001_initial'),
        ('users', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to='users.customer', verbose_name='Reviewing Customer Profile'),
        ),
        migrations.AddField(
            model_name='rating',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='sales.order', verbose_name='Related Order'),
        ),
        migrations.AddField(
            model_name='customercartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='customers.customercart', verbose_name='Cart'),
        ),
        migrations.AddField(
            model_name='customercartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='customercart',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_carts', to='stores.branch', verbose_name='Associated Branch'),
        ),
        migrations.AddField(
            model_name='customercart',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='users.customer', verbose_name='Customer Profile'),
        ),
        migrations.AlterUniqueTogether(
            name='customercartitem',
            unique_together={('cart', 'product')},
        ),
        migrations.AddConstraint(
            model_name='customercart',
            constraint=models.UniqueConstraint(condition=models.Q(('customer__isnull', False), ('is_active', True)), fields=('customer', 'branch'), name='unique_active_customer_cart_per_branch'),
        ),
        migrations.AddConstraint(
            model_name='customercart',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('session_key__isnull', False)), fields=('session_key', 'branch'), name='unique_active_guest_cart_per_branch'),
        ),
    ]
