# Generated by Django 4.2.22 on 2025-07-01 16:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingSystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Configuration Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('api_base_url', models.URLField(verbose_name='API Base URL')),
                ('api_key', models.CharField(max_length=255, verbose_name='API Key (or Token)')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active Configuration')),
                ('system_type', models.CharField(choices=[('REWAA', 'Rewaa'), ('QUICKBOOKS', 'QuickBooks Online'), ('XERO', 'Xero'), ('ZATCA_EINV', 'ZATCA E-Invoicing')], default='ZATCA_EINV', max_length=50, verbose_name='Accounting/Integration System Type')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Synced At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Accounting System Configuration',
                'verbose_name_plural': 'Accounting System Configurations',
            },
        ),
        migrations.CreateModel(
            name='ProductSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_date', models.DateTimeField(auto_now_add=True, verbose_name='Sync Date')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('IN_PROGRESS', 'In Progress')], default='PENDING', max_length=15, verbose_name='Sync Status')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Sync Message')),
                ('products_synced', models.PositiveIntegerField(default=0, verbose_name='Products Synced')),
                ('errors_count', models.PositiveIntegerField(default=0, verbose_name='Errors Count')),
            ],
            options={
                'verbose_name': 'Product Sync Log',
                'verbose_name_plural': 'Product Sync Logs',
                'ordering': ['-sync_date'],
            },
        ),
        migrations.CreateModel(
            name='SaleInvoiceSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('RETRIED', 'Retried')], default='PENDING', max_length=10, verbose_name='Sync Status')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Sync Message')),
                ('sync_date', models.DateTimeField(auto_now_add=True, verbose_name='Sync Date')),
                ('accounting_invoice_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Accounting System Invoice ID')),
                ('app_commission_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='App Commission Rate (%)')),
                ('total_amount_before_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Amount Before Commission')),
                ('amount_sent_to_accounting', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Amount Sent to Accounting')),
            ],
            options={
                'verbose_name': 'Sale Invoice Sync Log',
                'verbose_name_plural': 'Sale Invoice Sync Logs',
                'ordering': ['-sync_date'],
            },
        ),
        migrations.CreateModel(
            name='ZatcaInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, null=True, unique=True, verbose_name='ZATCA UUID')),
                ('invoice_hash', models.CharField(blank=True, max_length=255, null=True, verbose_name='Invoice Hash')),
                ('cryptographic_stamp', models.TextField(blank=True, null=True, verbose_name='Cryptographic Stamp')),
                ('qr_code_string', models.TextField(blank=True, null=True, verbose_name='QR Code Data (Base64)')),
                ('xml_content', models.TextField(blank=True, null=True, verbose_name='Fatoora XML Content')),
                ('zatca_response', models.JSONField(blank=True, null=True, verbose_name='Last ZATCA API Response')),
                ('last_submission_date', models.DateTimeField(blank=True, null=True, verbose_name='Last ZATCA Submission Date')),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending Processing'), ('ACCEPTED', 'Accepted by ZATCA'), ('REJECTED', 'Rejected by ZATCA'), ('REPORTED', 'Reported (Phase 1)'), ('CLEARED', 'Cleared (Phase 2)'), ('FAILED_VALIDATION', 'Failed ZATCA Validation'), ('UNKNOWN', 'Unknown Status')], default='PENDING', max_length=20, verbose_name='ZATCA Processing Status')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='ZATCA Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'ZATCA E-Invoice Detail',
                'verbose_name_plural': 'ZATCA E-Invoice Details',
                'ordering': ['-created_at'],
            },
        ),
    ]
