# Generated by Django 4.2.22 on 2025-07-01 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zatcainvoice',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zatca_details', to='sales.order', verbose_name='Related Order/Invoice'),
        ),
        migrations.AddField(
            model_name='saleinvoicesynclog',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_invoice_sync_logs', to='integrations.accountingsystemconfig', verbose_name='Accounting System Configuration'),
        ),
        migrations.AddField(
            model_name='saleinvoicesynclog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_sync_logs', to='sales.order', verbose_name='Related Order'),
        ),
        migrations.AddField(
            model_name='productsynclog',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sync_logs', to='integrations.accountingsystemconfig', verbose_name='Accounting System Configuration'),
        ),
    ]
