# Generated by Django 4.2.22 on 2025-07-01 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='store',
            name='permission_profile',
            field=models.ForeignKey(blank=True, help_text='Assign a permission profile to this store for operational access.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.storepermissionprofile', verbose_name='Permission Profile'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_type',
            field=models.ForeignKey(blank=True, help_text='Categorize the store type (e.g., Restaurant, Retail, Service).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.storetype', verbose_name='Store Type'),
        ),
        migrations.AddField(
            model_name='store',
            name='user',
            field=models.OneToOneField(blank=True, help_text='The primary user account associated with this store.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_account', to=settings.AUTH_USER_MODEL, verbose_name='Primary Store Account'),
        ),
        migrations.AddField(
            model_name='branch',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='branch',
            name='manager_employee',
            field=models.OneToOneField(blank=True, help_text='The user account assigned as the manager of this branch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branch', to=settings.AUTH_USER_MODEL, verbose_name='Branch Manager Account'),
        ),
        migrations.AddField(
            model_name='branch',
            name='permission_profile',
            field=models.ForeignKey(blank=True, help_text='Assign a permission profile to this branch for operational access.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.branchpermissionprofile', verbose_name='Permission Profile'),
        ),
        migrations.AddField(
            model_name='branch',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='stores.store', verbose_name='Store'),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('store', 'name')},
        ),
    ]
